import type { Model } from "@earendil-works/pi-ai";

const BASE_URL = "https://ark.cn-beijing.volces.com/api/coding/v3";

export const ARK_CODING_PLAN_MODELS = {
  "doubao-seed-evolving": {
    id: "doubao-seed-evolving",
    provider: "ark-agent-plan",
    name: "Doubao-Seed-Evolving",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 262144,
    maxTokens: 262144,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "doubao-seed-2.0-code": {
    id: "doubao-seed-2.0-code",
    provider: "ark-coding-plan",
    name: "Doubao-Seed-2.0-code",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 262144,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "doubao-seed-2.0-pro": {
    id: "doubao-seed-2.0-pro",
    provider: "ark-coding-plan",
    name: "Doubao-Seed-2.0-pro",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 262144,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "deepseek-v4-pro": {
    id: "deepseek-v4-pro",
    provider: "ark-coding-plan",
    name: "DeepSeek V4 Pro",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text"],
    contextWindow: 1000000,
    maxTokens: 384000,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: null,
      high: "high",
      xhigh: "max",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "deepseek-v4-flash": {
    id: "deepseek-v4-flash",
    provider: "ark-coding-plan",
    name: "DeepSeek V4 Flash",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text"],
    contextWindow: 1000000,
    maxTokens: 384000,
    compat: {
      supportsDeveloperRole: false,
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: null,
      high: "high",
      xhigh: "max",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "glm-5.2": {
    id: "glm-5.2",
    provider: "ark-coding-plan",
    name: "GLM-5.2",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text"],
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "kimi-k2.7-code": {
    id: "kimi-k2.7-code",
    provider: "ark-coding-plan",
    name: "Kimi K2.7 Code",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 262144,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
  "minimax-m3": {
    id: "minimax-m3",
    provider: "ark-coding-plan",
    name: "Minimax M3",
    api: "openai-completions",
    baseUrl: BASE_URL,
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 512000,
    maxTokens: 128000,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "deepseek",
    },
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  } satisfies Model<"openai-completions">,
};
