/**
 * Embed the LangGraph generator's built-in tool sources into a committed TS
 * manifest so the (browser-side, build-step-free) generator can copy them into
 * generated projects.
 *
 * Reads every `*.py` under
 * `packages/core/src/generator/langgraph/tools/built-in/` and writes
 * `built-in-sources.generated.ts` (map of tool name → source). The tool name is
 * the filename stem, which matches the app's built-in tool `name` 1:1.
 *
 * Run with `bun scripts/gen-langgraph-tools.ts` (or `mise run gen:langgraph-tools`).
 * A sibling test (`built-in-sources.test.ts`) fails if this file drifts.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const LANGGRAPH_DIR = path.join(
  import.meta.dir,
  "..",
  "packages/core/src/generator/langgraph"
);
const BUILTIN_DIR = path.join(LANGGRAPH_DIR, "tools/built-in");
const VARIABLES_PY = path.join(LANGGRAPH_DIR, "variables.py");
const OUT_FILE = path.join(LANGGRAPH_DIR, "tools/built-in-sources.generated.ts");

/** Read the `.py` tool files into a name→source map (sorted by name). */
export async function readBuiltinToolSources(): Promise<Record<string, string>> {
  const entries = await readdir(BUILTIN_DIR);
  const pyFiles = entries.filter((e) => e.endsWith(".py")).sort();
  const sources: Record<string, string> = {};
  for (const file of pyFiles) {
    const name = file.slice(0, -".py".length);
    sources[name] = await readFile(path.join(BUILTIN_DIR, file), "utf8");
  }
  return sources;
}

/** Read the shared `variables.py` (prompt-variable helpers) source. */
export async function readVariablesSource(): Promise<string> {
  return readFile(VARIABLES_PY, "utf8");
}

/** Render the generated TS module from a name→source map + variables.py. */
export function renderManifest(
  sources: Record<string, string>,
  variablesSource: string
): string {
  const entries = Object.entries(sources)
    .map(([name, source]) => `  ${JSON.stringify(name)}: ${JSON.stringify(source)},`)
    .join("\n");
  return `// GENERATED by scripts/gen-langgraph-tools.ts — do not edit by hand.
// Run \`bun scripts/gen-langgraph-tools.ts\` after changing built-in/*.py or variables.py.

/** Built-in tool name → Python source, embedded for the LangGraph generator. */
export const BUILTIN_TOOL_SOURCES: Record<string, string> = {
${entries}
};

/** The shared \`variables.py\` (current_date / available_skills) source. */
export const VARIABLES_PY_SOURCE = ${JSON.stringify(variablesSource)};
`;
}

if (import.meta.main) {
  const sources = await readBuiltinToolSources();
  const variablesSource = await readVariablesSource();
  await writeFile(OUT_FILE, renderManifest(sources, variablesSource), "utf8");
  console.info(
    `Wrote ${Object.keys(sources).length} built-in tool sources + variables.py to ${path.relative(
      path.join(import.meta.dir, ".."),
      OUT_FILE
    )}`
  );
}
