import { Type, type Static } from "typebox";

import { ImageContent, TextContent } from "./contents";
import {
  ProviderHostedToolActivity,
  ResponseOutputItem,
} from "./provider-hosted-tool";
import { ToolCall } from "./tools";
import { ModelUsage } from "./usage";

/**
 * Client-observed timing for one completed assistant/model step.
 *
 * Both values start immediately before the streaming request is dispatched.
 * `firstTokenMs` ends at the first non-empty model delta, while `durationMs`
 * ends when the completed assistant message is received.
 */
export const AssistantMessageTiming = Type.Object({
  firstTokenMs: Type.Optional(Type.Number({ minimum: 0 })),
  durationMs: Type.Number({ minimum: 0 }),
});
export type AssistantMessageTiming = Static<typeof AssistantMessageTiming>;

/**
 * The allowed content types of a user message.
 */
export const UserMessageContent = Type.Union([TextContent, ImageContent]);
export type UserMessageContent = TextContent | ImageContent;

/**
 * A message sent from user.
 */
export const UserMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("user"),

  /**
   * The content of the message.
   */
  content: Type.Array(UserMessageContent),
});
export type UserMessage = Static<typeof UserMessage>;

/**
 * The allowed content types of a assistant message.
 */
export const AssistantMessageContent = Type.Union([TextContent]);

/**
 * A message generated by AI.
 */
export const AssistantMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("assistant"),

  /**
   * The content of the message.
   */
  content: Type.Array(AssistantMessageContent),

  /**
   * The thinking of the message.
   */
  thinking: Type.Optional(Type.String()),

  /**
   * The tool calls of the message.
   */
  toolCalls: Type.Optional(Type.Array(ToolCall)),

  providerHostedToolActivities: Type.Optional(
    Type.Array(ProviderHostedToolActivity)
  ),

  responseOutputItems: Type.Optional(Type.Array(ResponseOutputItem)),

  /**
   * Provider-reported token usage for this completed assistant/model step.
   */
  usage: Type.Optional(ModelUsage),

  /**
   * Client-observed response timing for this completed assistant/model step.
   */
  timing: Type.Optional(AssistantMessageTiming),
});
export type AssistantMessage = Static<typeof AssistantMessage>;

/**
 * The union type of the message.
 */
export const Message = Type.Union([UserMessage, AssistantMessage]);
export type Message = UserMessage | AssistantMessage;

/**
 * The plain text of a message: its text content parts joined by newlines.
 * Non-text content (e.g. images) is ignored.
 */
export function getMessageText(message: Message): string {
  const parts: string[] = [];
  for (const c of message.content) {
    if (c.type === "text") {
      parts.push(c.text);
    }
  }
  return parts.join("\n");
}
